-- ============================================================================
-- ElevateMe Flyway V12 — RLS runtime allow-policy + identity sequence grants
-- Postgres 14 compatible. Idempotent. Depends on V1–V11.
--
-- Root cause (E2): every app.* table has ENABLE ROW LEVEL SECURITY with only a
-- deny_all policy FOR ALL TO anon, authenticated. Tables are owned by the
-- migration owner (elevateme_owner / Flyway user), so RLS APPLIES to the
-- runtime roles (app_runtime, elevateme_app): with RLS enabled and no policy
-- FOR the current user, PG14 denies ALL rows despite table GRANTs. Runtime
-- reads/writes therefore return zero rows / fail.
--
-- Fix: add a permissive allow_runtime policy FOR ALL TO app_runtime,
-- elevateme_app USING (true) WITH CHECK (true) on every app.* table.
-- deny_all for anon/authenticated is left UNTOUCHED (direct Data API stays
-- denied). Java JDBC scoping remains authoritative for row ownership.
--
-- Root cause (E3): app.audit_events.id is BIGINT GENERATED BY DEFAULT AS
-- IDENTITY (V4), whose backing sequence app.audit_events_id_seq was never
-- granted to the runtime roles, so runtime INSERTs into audit_events fail
-- with permission denied on the sequence. (grep SERIAL/IDENTITY across
-- database/migrations finds ONLY this identity column; the only other
-- sequence is app.elevate_me_seq, already granted in V1/V5.1.)
-- Fix: GRANT USAGE, SELECT on the identity sequence (+ re-assert
-- elevate_me_seq) to both runtime roles, plus a generic backstop over all
-- sequences in schema app so future identity columns are covered.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE SCHEMA IF NOT EXISTS app;

-- Roles must exist for POLICY / GRANT to parse on vanilla PG14 (V1/V5 pattern).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
    CREATE ROLE app_runtime NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'elevateme_app') THEN
    CREATE ROLE elevateme_app NOLOGIN;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA app TO app_runtime, elevateme_app;

-- ----------------------------------------------------------------------------
-- 1. Runtime allow-policy on every app.* table (deny_all untouched).
-- Idempotent via pg_policies guard; to_regclass guard keeps skeleton DBs safe.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'institutes', 'profiles', 'institute_memberships',
    'programs', 'sessions', 'registrations', 'session_attendance',
    'rubric_versions', 'rubric_criteria',
    'evaluation_assignments', 'evaluations', 'evaluation_revisions',
    'evaluation_scores', 'report_releases',
    'guest_invitations', 'guest_invitation_students', 'guest_sessions',
    'recommendations', 'recommendation_recipients',
    'development_assignments', 'payment_verifications',
    'query_threads', 'query_messages',
    'notifications', 'outbox_events',
    'criterion_alerts', 'comment_bank_entries',
    'audit_events',
    'development_events'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    IF to_regclass(format('app.%s', t)) IS NULL THEN
      CONTINUE;
    END IF;
    EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (SELECT 1 FROM pg_policies
                   WHERE schemaname = 'app' AND tablename = t
                     AND policyname = 'allow_runtime') THEN
      EXECUTE format('CREATE POLICY allow_runtime ON app.%I FOR ALL TO app_runtime, elevateme_app USING (true) WITH CHECK (true)', t);
    END IF;
  END LOOP;
END
$$;

-- ----------------------------------------------------------------------------
-- 2. Identity / sequence grants for runtime inserts (E3).
-- audit_events_id_seq backs audit_events.id IDENTITY (V4). elevate_me_seq
-- re-asserted for both roles (V1 granted elevateme_app, V5.1 app_runtime).
-- Idempotent via to_regclass guard; GRANT itself is re-runnable.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF to_regclass('app.audit_events_id_seq') IS NOT NULL THEN
    EXECUTE 'REVOKE ALL ON SEQUENCE app.audit_events_id_seq FROM anon, authenticated, PUBLIC';
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE app.audit_events_id_seq TO app_runtime, elevateme_app';
  END IF;
  IF to_regclass('app.elevate_me_seq') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE app.elevate_me_seq TO app_runtime, elevateme_app';
  END IF;
END
$$;

-- Generic backstop: any other / future identity sequences in schema app.
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT sequence_schema, sequence_name
           FROM information_schema.sequences
           WHERE sequence_schema = 'app' LOOP
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %I.%I TO app_runtime, elevateme_app',
                   r.sequence_schema, r.sequence_name);
  END LOOP;
END
$$;

COMMENT ON POLICY allow_runtime ON app.programs IS 'V12: runtime JDBC access (app_runtime, elevateme_app). deny_all for anon/authenticated untouched; Java JDBC scoping authoritative.';
